"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-x7&_v7a=!eh3=y@a#7#+8h7*m69)+ef0^nb=askchbp4lp5$0c'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # my apps
    'payments',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR/'templates', ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}








# Ensure this ends exactly with /v1.2.0-beta/
# https://onecodesoft.com/blogs/bkash-sandbox-credentials-for-payment-gateway-testing

BKASH_SANDBOX_URL = "https://tokenized.sandbox.bka.sh/v1.2.0-beta/"

BKASH_APP_KEY = "4f6o0cjiki2rfm34kfdadl1eqq"
BKASH_APP_SECRET = "2is7hdktrekvrbljjh44ll3d9l1dtjo4pasmjvs5vl5qr3fug4b"
BKASH_USERNAME = "sandboxTokenizedUser02"
BKASH_PASSWORD = "sandboxTokenizedUser02@12345"

## These Does not work
# BKASH_APP_KEY = "5M7s90601iahj3b966ss1859"
# BKASH_APP_SECRET = "v69of6ms32bjuwftisg38unv6489b0246986g28ssbve48as929"
# BKASH_USERNAME = "sandbox_user"
# BKASH_PASSWORD = "sandbox_pass"

# # Reminders ...

# For a more complete integration, add these checks:
# - Save the generated merchantInvoiceNumber and expected amount before redirecting.
# - On callback, confirm bKash’s executed response matches that saved invoice, amount, and currency.
# - Save paymentID/trxID and reject duplicate paymentIDs, so a callback cannot be processed twice.
# - Treat cancelled/failed statuses as separate outcomes for clearer messaging.
# - Optionally query the payment status after execute if you need reconciliation.
# The key principle is already present: never mark an order paid merely from callback query parameters—only after the server-side execute response says Completed.

# # GPT Help

# Use a database table for payments. The important part is making `paymentID` unique at the database level—don’t rely only on an `if` statement.

# ```python
# # payments/models.py
# class Payment(models.Model):
#     payment_id = models.CharField(max_length=100, unique=True)
#     trx_id = models.CharField(max_length=100, blank=True)
#     invoice = models.CharField(max_length=50, unique=True)
#     amount = models.DecimalField(max_digits=10, decimal_places=2)
#     status = models.CharField(max_length=20, default="PENDING")
# ```

# Your flow becomes:

# 1. Generate an invoice number.
# 2. Call bKash **create**.
# 3. Before redirecting to `bkashURL`, save its returned `paymentID`, your invoice number, amount, and `PENDING` status.
# 4. On callback, find that row by `paymentID`.
# 5. If it is already `COMPLETED`, do not execute again—show “already processed.”
# 6. Otherwise execute it. Only after bKash replies `Completed`, save `trxID` and set the row’s status to `COMPLETED`.

# Use `transaction.atomic()` plus `select_for_update()` while reading/updating the payment row, so two callback requests arriving at the same time cannot both process it.

# “Reconciliation” means independently checking bKash later against your own database.

# Example: bKash completes the payment, but your server times out before receiving the execute response. Your database may still say `PENDING`, even though the customer was charged. A reconciliation job/admin action calls bKash’s payment-status/query endpoint with the stored `paymentID`, then updates your database from `PENDING` to `COMPLETED` if bKash confirms it.

# It is a recovery/verification mechanism—not normally required after every successful execute call.


# # GPT changed

# Applied and migrated the full practice version.

# - A `Payment` database record now saves `paymentID`, `trxID`, invoice, amount, currency, gateway message, timestamps, and status.
# - After bKash create succeeds, the payment is saved as `PENDING` before redirecting.
# - The callback locks that record, sets it to `PROCESSING`, and executes bKash only once.
# - A repeated callback for a completed payment safely returns the saved success result without re-executing.
# - The execute/status responses must match the saved `paymentID`, invoice, amount, and currency before marking it `COMPLETED`.
# - Added an admin payment list and an admin-only reconciliation endpoint:
#   `POST /bkash/reconcile/<payment_id>/`
# - Added automated tests for saving a pending payment and rejecting a duplicate callback.

# Files added/changed:

# - [models.py](C:\Users\Administrator\Documents\Prof\bkash-practice\bkash%20-%20server-side%20authorization\payments\models.py)
# - [0001_initial.py](C:\Users\Administrator\Documents\Prof\bkash-practice\bkash%20-%20server-side%20authorization\payments\migrations\0001_initial.py)
# - [views.py](C:\Users\Administrator\Documents\Prof\bkash-practice\bkash%20-%20server-side%20authorization\payments\views.py)
# - [admin.py](C:\Users\Administrator\Documents\Prof\bkash-practice\bkash%20-%20server-side%20authorization\payments\admin.py)
# - [tests.py](C:\Users\Administrator\Documents\Prof\bkash-practice\bkash%20-%20server-side%20authorization\payments\tests.py)

# Verification passed: Django system checks and both payment-flow tests.

# The payment records will appear at `/admin/payments/payment/` after you create an admin user and sign in.